# Generated by Django 6.0.3 on 2026-08-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("campus", "name"), name="unique_facility_per_campus"
            ),
        ),
    ]
