# Generated by Django 6.0.3 on 2026-08-08 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Campuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "manager_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CampusDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_departments",
                        to="org.campus",
                    ),
                ),
                (
                    "head_of_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_campus_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_departments",
                        to="org.department",
                    ),
                ),
            ],
            options={
                "ordering": ["campus", "department"],
            },
        ),
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_types",
                        to="org.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campus_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="org.campusdepartment",
                    ),
                ),
                (
                    "hos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="org.sectiontype",
                    ),
                ),
            ],
            options={
                "ordering": ["campus_department", "section_type"],
            },
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location_details",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the ticket creation wizard should collect location information.",
                    ),
                ),
                (
                    "section_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sections",
                        to="org.sectiontype",
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sub_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="org.subsection",
                    ),
                ),
            ],
            options={
                "ordering": ["sub_section", "name"],
            },
        ),
        migrations.CreateModel(
            name="SectionTechnician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_links",
                        to="org.section",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_section_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_links",
                        to="org.subsection",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "sub_section", "user"],
            },
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_department_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_department_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="campusdepartment",
            constraint=models.UniqueConstraint(
                fields=("campus", "department"), name="unique_campus_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectiontype",
            constraint=models.UniqueConstraint(
                fields=("department", "name"), name="unique_section_type_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("campus_department", "section_type"),
                name="unique_section_per_campus_department_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsection",
            constraint=models.UniqueConstraint(
                fields=("section_type", "name"),
                name="unique_sub_section_name_per_section_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsection",
            constraint=models.UniqueConstraint(
                fields=("section_type", "code"),
                name="unique_sub_section_code_per_section_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceitem",
            constraint=models.UniqueConstraint(
                fields=("sub_section", "name"),
                name="unique_service_item_per_sub_section",
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontechnician",
            index=models.Index(
                fields=["section", "sub_section"], name="sectech_section_sub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectiontechnician",
            constraint=models.UniqueConstraint(
                fields=("user", "section", "sub_section"),
                name="unique_technician_section_sub_section",
            ),
        ),
    ]
