# Generated by Django 6.0.3 on 2026-08-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsection",
            name="location_details",
        ),
    ]
