"""
Django settings for resolver project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / ".env")


SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is not set.")

DEBUG = os.getenv("DEBUG", "False") == "True"

# Allow all hosts in production for now (more secure to specify exact domains)
ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Django's CSRF Origin check compares against this explicitly (not ALLOWED_HOSTS) —
# without it, POSTs to /admin/login/ fail with "Origin checking failed" once the
# site is served over HTTPS behind a proxy (Render/Cloudflare).
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if o.strip()
]

# Render terminates TLS at its proxy and forwards plain HTTP with this header —
# without it, request.is_secure() is False and secure cookies/CSRF checks misbehave.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    # Modern admin interface (must be before django.contrib.admin)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 8-app domain layer
    "apps.common",
    "apps.accounts",
    "apps.org",
    "apps.sla",
    "apps.facilities",
    "apps.tickets",
    "apps.analytics",
    "apps.notifications",
    # third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "whitenoise.runserver_nostatic",
]

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Resolver",
    "SITE_HEADER": "Maintenance Ticket Management",
    "SITE_URL": "/",
    "SITE_SYMBOL": "🎫",  # Ticket emoji for branding
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "apps.common.admin.environment_callback",
    "DASHBOARD_CALLBACK": "apps.common.admin.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Ticket Management",
                "separator": True,
                "items": [
                    {
                        "title": "Tickets",
                        "icon": "assignment",
                        "link": "/admin/tickets/ticket/",
                        "badge": "apps.common.admin.ticket_count_badge",
                    },
                    {
                        "title": "Comments",
                        "icon": "comment",
                        "link": "/admin/tickets/ticketcomment/",
                    },
                    {
                        "title": "Feedback",
                        "icon": "star_rate",
                        "link": "/admin/tickets/ticketfeedback/",
                    },
                ],
            },
            {
                "title": "System Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/accounts/customuser/",
                        "badge": "apps.common.admin.user_count_badge",
                    },
                    {
                        "title": "Role Assignments",
                        "icon": "assignment_ind",
                        "link": "/admin/accounts/roleassignment/",
                    },
                    {
                        "title": "Campuses",
                        "icon": "location_city",
                        "link": "/admin/org/campus/",
                    },
                    {
                        "title": "Departments",
                        "icon": "apartment",
                        "link": "/admin/org/department/",
                    },
                    {
                        "title": "Sections",
                        "icon": "category",
                        "link": "/admin/org/section/",
                    },
                    {
                        "title": "Facilities",
                        "icon": "business",
                        "link": "/admin/facilities/facility/",
                        "badge": "apps.common.admin.facility_count_badge",
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add whitenoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Add CORS middleware (must be before CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "resolver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "resolver.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if available (Render), otherwise use individual env vars
if os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=0,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            # CONN_MAX_AGE=0: let Neon's pooler manage connection reuse.
            # Keeping connections alive in Django (300s) matched Neon's 5-min suspend
            # window exactly, causing DNS-resolution failures on reconnect after idle.
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": True,
            # Use fast in-memory SQLite for the test runner to avoid Neon remote latency
            "TEST": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": ":memory:",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Explicitly define static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Additional static files directories (if needed)
STATICFILES_DIRS = []

# WhiteNoise configuration - use CompressedManifestStaticFilesStorage for production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Use CompressedManifestStaticFilesStorage for better caching
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# WhiteNoise settings for better static file serving
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MANIFEST_STRICT = False  # Don't fail on missing files
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "zip",
    "gz",
    "tgz",
    "bz2",
    "tbz",
    "xz",
    "br",
]
WHITENOISE_MIMETYPES = {
    ".js": "application/javascript",
    ".css": "text/css",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
#
# Deployment-specific origins belong in the CORS_ALLOWED_ORIGINS env var, not
# here — the defaults below are the local dev and preview ports only. A commit
# that hard-codes a deployment hostname makes local and deployed builds diverge
# silently, which is how a local production build ended up posting to the live
# backend (see frontend/.env.production).

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        # 5173 = vite dev, 4173 = vite preview (PWA/phone testing)
        "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173",
    ).split(",")
    if o.strip()
]

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Optional: Allow all origins in development (NOT recommended for production)
# CORS_ALLOW_ALL_ORIGINS = True

SIMPLE_JWT = {
    # Short-lived on purpose: jwt_refresh() re-derives role/scope claims from
    # the DB on every rotation, so this window bounds how long a promoted/
    # demoted user can keep acting on a stale role before their next silent
    # refresh picks up the change.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "sub",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}
