# Generated by Django 6.0.3 on 2026-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Optional — just in case the technician needs to call.",
                max_length=32,
            ),
        ),
    ]
