# Generated by Django 6.0.3 on 2026-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="pending_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("material_shortage", "Materials not in store"),
                    ("awaiting_procurement", "Awaiting procurement"),
                    ("awaiting_approval", "Awaiting approval"),
                    ("awaiting_contractor", "Awaiting contractor"),
                    ("specialist_required", "Specialist required"),
                    ("access_unavailable", "Cannot access the area"),
                    ("scope_clarification", "Scope needs clarification"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Set while status is 'pending'; cleared when work resumes.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="pending_reason_note",
            field=models.TextField(
                blank=True,
                help_text="Free text alongside the code — required when the reason is 'other'.",
            ),
        ),
    ]
