# Generated by Django 6.0.3 on 2026-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_pending_reason_ticket_pending_reason_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pending_reason',
            field=models.CharField(blank=True, choices=[('awaiting_materials', 'Materials not in store'), ('awaiting_procurement', 'Order placed, not yet delivered'), ('awaiting_approval', 'Awaiting approval'), ('awaiting_labour', 'No technician available'), ('awaiting_contractor', 'Awaiting contractor'), ('awaiting_requester', 'Waiting on the requester'), ('access_unavailable', 'Cannot access the area'), ('scope_clarification', 'Scope needs clarification'), ('other', 'Other')], default='', help_text="Set while status is 'pending'; cleared when work resumes.", max_length=24),
        ),
    ]
